/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JA.Lesson.Gradle.Homework;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
